### PR TITLE
Use console.error in default logger

### LINKED ISSUE #2: Log to stderr by default
Thank you for making this wonderful library!

I think it's better to write to stderr than stdout by default. By UNIX convension stdout and stdin are for process communication.

### PR DESCRIPTION
**Pull request by locriacyber**
Close #2

### CODE REVIEW

**Comment by cknight** [comment]
Thank you for your suggestion.  This has been addressed by https://github.com/onjara/optic/commit/8396b0b88c6e04a50de0ecc843aa3e13148a76f3.

**Comment by locriacyber** [comment]
Is it possible to make optic output on stderr on Node or deno? Logging on stdout is very weird, especially with utilities like `wget` and `curl` that need to use stdout to output data.

**Comment by cknight** [comment]
It is fairly standard practice to output console data to either stdout or stderr depending on the severity.  For example, Winston, a very popular Node logging library [does just this](https://github.com/winstonjs/winston/blob/master/lib/winston/transports/console.js#L44).  It's very easy to use the extensibility of my library to achieve your goal however:
```typescript
const logger = new Logger();
const errorConsoleStream = new class extends ConsoleStream {
  override handle(logRecord: LogRecord): boolean {
    if (this.minLevel > logRecord.level) return false;
    console.error(this.format(logRecord));
    return true;
  }
}();

logger.addStream(errorConsoleStream);
```

**Comment by locriacyber** [comment]
Logging to stdout is just bad practice, unless you don't care about using stdout.

**Pull request closed without merging**
